### ISSUE TITLE
Keys for First & Last image

### ISSUE THREAD

**Issue by smaragdus** [asimba/pybpgviewer#2]
I would appreciate if **Simple BPG Image viewer** has shortcut keys for the first and for the last **BPG** file inside the browsed folder, for example:

- 'Home' key navigates to first **BPG** file inside browsed folder;
- 'End' key navigates to last **BPG** file inside browsed folder;

Of course the shortcut keys may be different but for me 'Home' and 'End' keys seem logical (at least on Windows).

A shortcut key for navigating to first/last image inside a folder would be particularly useful if the folder contains many **BPG** files.

**Comment by asimba** [comment]
Ok. No problem. This feature will be available at next release (2-3 months, in the existance of free time, cause first of all I need to test packages for all versions of "Bionic Beaver").

**Comment by smaragdus** [comment]
@asimba 
Thanks.

**Comment by asimba** [comment]
You're welcome!

**Comment by asimba** [comment]
Done.

**Comment by smaragdus** [comment]
@asimba 
Thank you for adding keys for first and last image, for me these keys add even more convenience for browsing.

**Comment by asimba** [comment]
You're welcome! :)
