### ISSUE TITLE
On Top

### ISSUE THREAD

**Issue by smaragdus** [asimba/pybpgviewer#3]
@asimba 

In the future you may add a new hot key:

- On Top (or Always on Top)

'Ctrl+T' seems a natural key combination for such function.

As I mentioned in [another issue](https://github.com/asimba/pybpgviewer/issues/1) I use an [external tool](https://github.com/AlexanderPro/SmartSystemMenu) for making **Simple BPG Image viewer** 'On Top' but native support for 'On Top' would be better. This would be a good supplement to 'Drag&Drop'.

How I imagine this implemented- 'Ctrl+T' toggles 'On Top' on/off- when first pressed 'Ctrl+T' triggers 'On Top' mode, when 'On Top' is active pressing 'Ctrl+T' switches back to normal mode.

**Comment by asimba** [comment]
Ok. I'll think about it.

**Comment by asimba** [comment]
Working already in progess. :)

**Comment by smaragdus** [comment]
@asimba 
Thank you very much!

**Comment by asimba** [comment]
You're welcome!
