### ISSUE TITLE
static binaries

### ISSUE THREAD

**Issue by ropucyka** [asimba/pybpgviewer#5]
Подскажите, а для чего нужны в релизе **bpg-0.9.8-static-binaries-win64.zip**
с их помощью можно конвертировать .bpg?

В документации автора формата указано:
_**by default bpgenc uses the x265. You can compile the much
slower but more efficient JCTVC encoder**_
а тогда какой кодировщик использован в этих бинарниках?

Не очень разбираюсь, а подробного описания к файлам в релизе найти не удалось.

**Comment by asimba** [comment]
Это скомпилированные оригинальные утилиты. Присутствуют оба кодека.

вт, 21 апр. 2020 г., 0:55 ropucyka <notifications@github.com>:

**Comment by ropucyka** [comment]
Оба?! Вот просто спасибо. И за быстрый ответ тоже.

**Comment by asimba** [comment]
Пожалуйста. Вьювер был написан потому что мне оригинал не понравился. Для
кодирования удобнее использовать BPGConv (
http://www.romeolight.com/products/bpgconv/ ).

вт, 21 апр. 2020 г., 18:22 ropucyka <notifications@github.com>:
