### ISSUE TITLE
x32 version [question]

### ISSUE THREAD

**Issue by smaragdus** [asimba/pybpgviewer#6]
@asimba 

Hello,

I am glad that you still maintain [Simple BPG Image viewer](https://github.com/asimba/pybpgviewer)- I see that there is a new release- [1.27](https://github.com/asimba/pybpgviewer/releases/tag/v1.27), which is x64 version only. Is x32 version discontinued?

Regards

**Comment by asimba** [comment]
Hello! Short answer is "yes". But... At this time I need to reinstall
"windows 10 x86" and "macOS" VMs and then... Maybe...

пн, 18 мая 2020 г., 19:09 smaragdus <notifications@github.com>:

**Comment by smaragdus** [comment]
@smaragdus 

Thanks for the quick reply!

I am using Windows 8 x64. But I also have an old x32 machine- if needed I may use the previous version ([1.26](https://github.com/asimba/pybpgviewer/releases/tag/v1.26)) on it.

Did you keep a change log? What is new in version [1.27](https://github.com/asimba/pybpgviewer/releases/tag/v1.27)?

Regards

**Comment by asimba** [comment]
Ok. 🙂 Update details:
1) there are no more temporary files at all (i.e. "FIFO"s);
2) BPG decoder is moved to dynamic link library from separate EXE-file;
3) some code modifications were made for meet Python 3 platform
requirements;
4) the abandoned package "py2exe" has been replaced by the "cx_freeze"
(windows only; 😢 good bye almost "monolithic  executables").

пн, 18 мая 2020 г., 20:10 smaragdus <notifications@github.com>:

**Comment by smaragdus** [comment]
@asimba 

Thank you for update information about version [1.27](https://github.com/asimba/pybpgviewer/releases/tag/v1.27).

In the future you might publish a change log file in [master branch](https://github.com/asimba/pybpgviewer) so that the users would be able to see what has changed in new releases.

Regards

**Comment by asimba** [comment]
You are welcome! May be later. But for now I am fighting against fresh "quicklook" API in macOS 10.15.

**Comment by asimba** [comment]
Done! :)
[x86 package](https://github.com/asimba/pybpgviewer/releases/download/v1.28/bpgviewer-1.28-win32-portable.7z) / [x86 installer](https://github.com/asimba/pybpgviewer/releases/download/v1.28/bpgviewer-1.28-win32-setup.exe)

**Comment by smaragdus** [comment]
@asimba 

Excellent! I downloaded version [1.28](https://github.com/asimba/pybpgviewer/releases/tag/v1.28), did a brief testing and everything seems fine with the latest release. I just noticed that the file version of the x64 executable (**bpgviewer.exe**) is **1.27.0.0**.

Most likely I will never need the x32 version at all and also I keep almost all previous versions (since 1.17) yet I am glad that you released x32 version. If it happens that in the future you choose to discontinue the x32 version you may keep the compiled binaries for older versions in [Releases](https://github.com/asimba/pybpgviewer/releases) page so that people who use old x32 machines could get your nice viewer. I really appreciate your work. Have a nice summer!

Best regards

**Comment by asimba** [comment]
> version of the x64 executable (**bpgviewer.exe**) is **1.27.0.0**.

That's right. Only "bpgdec.dll" was changed. You're welcome! :)
